# nixpacks.toml

[phases.setup]
# These are the OS-level dependencies required to compile mysqlclient
nixPkgs = ["python311", "mysql80", "pkg-config", "gcc"]

[phases.install]
# Standard python installation
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
# Prepare your static files for Whitenoise
cmds = ["cd backend && python manage.py collectstatic --noinput"]
