# nixpacks.toml

[phases.setup]
# These are the OS-level dependencies required to compile mysqlclient
nixPkgs = ["python311", "mysql80", "pkg-config", "gcc"]

[phases.install]
# Standard python installation
cmds = ["python -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt"]

[phases.build]
# Prepare your static files for Whitenoise
cmds = ["/opt/venv/bin/python manage.py collectstatic --noinput"]

