# Generated by Django 5.2.6 on 2026-04-19 13:17

import api.models
import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('max_tickets_per_user', models.PositiveIntegerField(default=1, help_text='Max tickets a single user can book')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Max. total capacity for the event. Leave blank for unlimited.', null=True)),
                ('location_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('physical_location', models.CharField(blank=True, max_length=255, null=True)),
                ('google_maps_link', models.TextField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator()])),
                ('virtual_location', models.TextField(blank=True, help_text='Meeting link for online events', null=True)),
                ('register_link', models.TextField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_native', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='event_posters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), api.models.validate_image_size])),
                ('is_paid_event', models.BooleanField(default=False)),
                ('payment_qr_image', models.ImageField(blank=True, null=True, upload_to='payment_qr_img/')),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('age_restriction_cutoff', models.DateField(blank=True, null=True)),
                ('collect_phone', models.BooleanField(default=False)),
                ('collect_college_school', models.BooleanField(default=False)),
                ('collect_student_id', models.BooleanField(default=False)),
                ('event_contacts', models.JSONField(blank=True, default=list, help_text='Stores POCs as a list of dicts')),
                ('payout_settled', models.BooleanField(default=False, help_text='Check this box once you have manually transferred funds to the host.')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_event_id', models.CharField(db_index=True, help_text='The unique X-Razorpay-Event-Id header value', max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Processed Webhooks',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', through='api.EventCategory', to='api.category'),
        ),
        migrations.CreateModel(
            name='EventClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_clicks', to='api.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='event_docs/', validators=[api.models.validate_brochure_size])),
                ('name', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_type', models.CharField(choices=[('club', 'Club'), ('institution', 'Institution'), ('promoter', 'External Promoter')], default='club', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, help_text='Public-facing official email for the club/org', max_length=254, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clubs', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='host_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.hostprofile'),
        ),
        migrations.CreateModel(
            name='SchoolCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('campus', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'School/College',
                'ordering': ['name', 'campus'],
                'constraints': [models.UniqueConstraint(fields=('name', 'campus', 'city'), name='unique_school_college_campus_per_city')],
            },
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='school_college',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this is an external promoter. Select a college if this is a student club.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_clubs', to='api.schoolcollege'),
        ),
        migrations.AddField(
            model_name='event',
            name='restricted_to_schools_colleges',
            field=models.ManyToManyField(blank=True, help_text='If set, only students from this college can view & register.', related_name='internal_events', to='api.schoolcollege'),
        ),
        migrations.CreateModel(
            name='UnlistedSchoolCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('campus', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('request_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Unlisted School/College Requests',
                'ordering': ['-request_count'],
                'constraints': [models.UniqueConstraint(fields=('name', 'campus', 'city'), name='unique_unlisted_school_college_request')],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('unlisted_school_college_data', models.JSONField(blank=True, default=dict, help_text='Stores user input if they selected Other/Unlisted', null=True)),
                ('student_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('school_college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.schoolcollege')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('guest_data', models.JSONField(blank=True, default=dict, null=True)),
                ('ticket_code', models.CharField(db_index=True, default=api.models.generate_ticket_code, max_length=6, unique=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('refund_pending', 'Refund Pending'), ('refund_processed', 'Refund Processed')], default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.studentprofile')),
            ],
            options={
                'verbose_name_plural': 'Registrations',
            },
        ),
        migrations.AddConstraint(
            model_name='eventcategory',
            constraint=models.UniqueConstraint(fields=('event', 'category'), name='unique_event_category'),
        ),
        migrations.AddIndex(
            model_name='eventclick',
            index=models.Index(fields=['event', '-created_at'], name='api_eventcl_event_i_3f50b4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured', 'start_date'], name='event_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['host', '-start_date'], name='host_dashboard_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'payment_status'], name='api_registr_event_i_5269bb_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'is_checked_in'], name='api_registr_event_i_f1bf61_idx'),
        ),
    ]
