# Generated by Django 5.2.6 on 2026-04-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unlistedschoolcollege',
            name='unique_unlisted_school_college_request',
        ),
        migrations.RemoveField(
            model_name='event',
            name='payment_qr_image',
        ),
        migrations.AddConstraint(
            model_name='unlistedschoolcollege',
            constraint=models.UniqueConstraint(fields=('name', 'campus', 'city'), name='unique_unlisted_school_college_request', nulls_distinct=False),
        ),
    ]
