# Generated by Django 5.2.6 on 2026-02-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcollege',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
