# Generated by Django 5.2.6 on 2026-02-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_schoolcollege_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
