# Generated by Django 5.2.6 on 2026-04-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_unlistedschoolcollege_unique_unlisted_school_college_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Snapshot of the ticket price at the time of purchase.', max_digits=10),
        ),
    ]
