# Generated by Django 5.2.6 on 2026-04-30 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_registration_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='booking_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Groups multiple tickets bought in a single checkout session'),
        ),
    ]
