# Generated by Django 5.2.6 on 2026-05-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_registration_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostprofile',
            name='unlisted_school_college_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores user input if they selected Other/Unlisted', null=True),
        ),
    ]
